<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Templates\ChildPrimaryKeyProperty.tmpl" />
    <None Remove="Templates\Dto.tmpl" />
    <None Remove="Templates\ForeignKeyProperty.tmpl" />
    <None Remove="Templates\SchemaRepository.tmpl" />
    <None Remove="Templates\SchemaRepositoryAddType.tmpl" />
    <None Remove="Templates\SchemaRepositoryMethods.tmpl" />
    <None Remove="Templates\Wrapper.tmpl" />
    <None Remove="Templates\XrefLeftProperty.tmpl" />
    <None Remove="Templates\XrefRightProperty.tmpl" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\ChildPrimaryKeyProperty.tmpl" />
    <EmbeddedResource Include="Templates\Dto.tmpl" />
    <EmbeddedResource Include="Templates\ForeignKeyProperty.tmpl" />
    <EmbeddedResource Include="Templates\SchemaRepository.tmpl" />
    <EmbeddedResource Include="Templates\SchemaRepositoryAddType.tmpl" />
    <EmbeddedResource Include="Templates\SchemaRepositoryMethods.tmpl" />
    <EmbeddedResource Include="Templates\Wrapper.tmpl" />
    <EmbeddedResource Include="Templates\XrefLeftProperty.tmpl" />
    <EmbeddedResource Include="Templates\XrefRightProperty.tmpl" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\bam.base\bam.base\bam.base.csproj" />
    <ProjectReference Include="..\..\bam.configuration\bam.configuration\bam.configuration.csproj" />
    <ProjectReference Include="..\..\bam.data.schema\bam.data.schema\bam.data.schema.csproj" />
    <ProjectReference Include="..\..\bam.data\bam.data.config\bam.data.config.csproj" />
    <ProjectReference Include="..\..\bam.data\bam.data.firebird\bam.data.firebird.csproj" />
    <ProjectReference Include="..\..\bam.data\bam.data.mssql\bam.data.mssql.csproj" />
    <ProjectReference Include="..\..\bam.data\bam.data.mysql\bam.data.mysql.csproj" />
    <ProjectReference Include="..\..\bam.data\bam.data.oracle\bam.data.oracle.csproj" />
    <ProjectReference Include="..\..\bam.data\bam.data.postgres\bam.data.postgres.csproj" />
    <ProjectReference Include="..\..\bam.data\bam.data\bam.data.csproj" />
    <ProjectReference Include="..\..\bam.logging\bam.logging\bam.logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CodeAnalysis">
      <HintPath>..\..\..\..\..\.nuget\packages\microsoft.codeanalysis.common\4.11.0\lib\net8.0\Microsoft.CodeAnalysis.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
