namespace Bam.Data.Repositories
{
    /// <summary>
    /// Defines generic type-parameterized methods for schema repository operations.
    /// These are generic versions of the type-name-embedded methods generated by
    /// SchemaRepositoryMethods.hbs (e.g., OneWhere&lt;T&gt; instead of OneServerAccountDataWhere).
    /// </summary>
    public interface ISchemaRepository : IDaoRepository
    {
        void SetOneWhere<T>(IQueryFilter where) where T : new();
        T? GetOneWhere<T>(IQueryFilter where) where T : new();
        T? OneWhere<T>(IQueryFilter where) where T : new();
        IEnumerable<T> Where<T>(IQueryFilter where) where T : new();
        IEnumerable<T> TopWhere<T>(int count, IQueryFilter where) where T : new();
        long Count<T>() where T : new();
        long CountWhere<T>(IQueryFilter where) where T : new();
        Task BatchAll<T>(int batchSize, Action<IEnumerable<T>> processor) where T : new();
    }
}
